import { openVoice, disposeVoice } from './voice-client.js';
const $=s=>document.querySelector(s);
const day=()=>new Date().toLocaleDateString('en-CA');
const fresh=()=>({date:day(),meals:0,water:0,baths:0,meds:[],mood:null,events:[]});
let state;try{state=JSON.parse(localStorage.getItem('wheelgentic-care'));if(!state||state.date!==day()||!Array.isArray(state.events)||!Array.isArray(state.meds))state=fresh();}catch{state=fresh();}
let view='overview';let toastTimer;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('wheelgentic-care',JSON.stringify(state));}catch{toast('Storage unavailable. Your changes last for this session only.');}}
function ensureDay(){if(state.date!==day()){state=fresh();save();}}
function log(title,description,icon='✓'){ensureDay();state.events.unshift({title,description,icon,time:new Date().toISOString()});save();render();}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function activity(){return state.events.length?state.events.map(e=>`<div class="activity-row"><span class="activity-icon">${escape(e.icon)}</span><div><strong>${escape(e.title)}</strong><small>${escape(e.description)}</small></div><time>${new Date(e.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty-state">A fresh start for today.<br>Your meals, care moments, and check-ins will appear here as you log them.</div>';}
function meds(){return ['Morning','Evening'].map((m,i)=>`<div class="med-row"><span class="med-symbol">⊕</span><div><strong>${m} medication</strong><small>Demo entry · use your prescribed plan</small></div><button class="med-check" data-med="${i}" ${state.meds.includes(i)?'disabled':''}>${state.meds.includes(i)?'✓ Logged':'Log taken'}</button></div>`).join('');}
function render(){ensureDay();$('#today').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#stats').innerHTML=[['Meals enjoyed',state.meals,'meals','♧','Logged today',3],['Water breaks',state.water,'glasses','♒','Logged today · 250 ml each',8],['Personal care',state.baths,'sessions','♡','Completed today',1],['Medications',state.meds.length,'/ 2 logged','⊕','Sample schedule',2]].map(([label,n,unit,icon,note,total])=>`<div class="stat"><div class="stat-header">${label}<span class="stat-icon">${icon}</span></div><div class="stat-number">${n}<small>${unit}</small></div><div class="stat-bottom"><span>${note}</span><div class="bar"><i style="width:${Math.min(n/total*100,100)}%"></i></div></div></div>`).join('');$('#activity-list').innerHTML=activity();$('#med-list').innerHTML=meds();document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.toggle('selected',state.mood===b.dataset.mood);b.setAttribute('aria-pressed',state.mood===b.dataset.mood);});$('#mood-message').textContent=state.mood?`You checked in as ${state.mood.toLowerCase()}. Thanks for sharing.`:'Every feeling is welcome here.';if(view!=='overview')renderDetail();}
const pages={overview:['Overview','Your day, your way.','A little support for the things that matter. Let’s make today a good one.'],medications:['Medications','A little help with your routine.','Track what you have taken, following your own prescribed care plan.'],vitals:['Vitals & wellbeing','A window into your wellbeing.','A preview of your connected health dashboard.'],activity:['Activity journal','Your day, thoughtfully recorded.','All of today’s care moments, in one place.'],team:['Care circle','Keep your people close.','Prepare a daily update for the people who support you.']};
function navigate(next){view=next;const [label,title,sub]=pages[next];$('#page-label').textContent=label;$('#heading').textContent=title;$('#subheading').textContent=sub;$('#overview').hidden=next!=='overview';$('#detail-view').hidden=next==='overview';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===next));renderDetail();}
function renderDetail(){let html='';if(view==='medications')html=`<div class="notice">Demo tracker only. These are sample entries, not medication instructions. No pill dispenser or robotic arm is connected.</div><div class="section-card"><h2>Your daily check-ins</h2>${meds()}</div>`;if(view==='activity')html=`<div class="section-card"><h2>Today’s journal</h2>${activity()}</div>`;if(view==='vitals')html=`<div class="notice">Simulated readings for the interface preview. No sensors are connected and these numbers do not describe your health.</div><div class="detail-grid">${[['Heart rate','72','bpm'],['Blood oxygen','98','%'],['Temperature','36.7','°C']].map(([label,value,unit])=>`<div class="section-card"><h2>${label}</h2><div class="vital-number">${value} <small>${unit}</small></div><svg class="vital-wave" viewBox="0 0 260 55" aria-hidden="true"><path d="M0 35H35L45 24L53 42L63 8L72 48L82 29L92 35H140L150 24L158 42L168 8L177 48L187 29L197 35H260" fill="none" stroke="#97bfdc" stroke-width="2"/></svg><p class="sample-label">SIMULATED · SENSOR OFFLINE</p></div>`).join('')}</div>`;if(view==='team')html='<div class="section-card"><h2>Your care circle</h2><p class="empty-state">Share today’s meals, water breaks, personal care, and medication check-ins with your caretaker, nursing home, or family. Choose a recipient when preparing the report.</p><button class="primary" data-action="report">Prepare care report ↗</button></div>';$('#detail-view').innerHTML=html;}
function modal(html){disposeVoice();$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function close(){$('#modal').close();}
function report(){return `WHEELGENTIC · DAILY CARE REPORT\n${new Date().toLocaleDateString(undefined,{dateStyle:'full'})}\n\nMeals logged: ${state.meals}\nWater breaks: ${state.water} (${state.water*250} ml logged)\nBathing sessions completed: ${state.baths}\nSample medication entries logged: ${state.meds.length}/2\nMood: ${state.mood||'Not checked in'}\n\nACTIVITY\n${state.events.map(e=>`${new Date(e.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} — ${e.title}${e.description?' · '+e.description:''}`).join('\n')||'No activity logged yet.'}\n\nFrontend demo. Entries are self-reported. No hardware or health sensors connected.`;}
function action(id, recipient='Caretaker'){ensureDay();if(id==='report'){const recipients=['Caretaker','Nursing home','Family'];const selected=recipients.includes(recipient)?recipient:'Caretaker';modal(`<h2>Share your care report</h2><p>Review today's summary for your caretaker, nursing home, or family.</p><label for="report-recipient">Share with</label><select id="report-recipient">${recipients.map(name=>`<option${name===selected?' selected':''}>${name}</option>`).join('')}</select><div class="report-preview">${escape(report())}</div><label>Recipient email (for email draft)<input id="caretaker-email" type="email" placeholder="recipient@example.com" required></label><div class="modal-actions"><button class="primary" id="email-report">Open email draft ↗</button><button class="secondary" id="download-report">Download report ↓</button></div><p>No message is sent automatically. Send the draft from your email app.</p>`);return;}
if(id==='meds'){modal(`<h2>Medication check-in</h2><p>Log a dose only after you have taken it according to your prescribed plan. This demo does not dispense medication.</p><div id="modal-meds">${meds()}</div>`);return;}
if(id==='voice'){openVoice(modal);return;}
if(id==='bathe'){modal('<h2>A fresh moment for you.</h2><p>Preview an assisted bathing session. This only simulates the interface; it does not move hardware.</p><div class="session-state" id="session-state">Ready to preview · Four robotic arms offline</div><div class="modal-actions"><button class="primary" id="start-bath">Start demo session</button></div>');return;}
const info={eat:['Enjoy a meal','Record a meal you have already eaten.','Log meal','Meal enjoyed','meals'],drink:['A little hydration break','Record a glass of water you have already had (250 ml).','Log water','Water break','water'],comfort:['Find your comfortable','Record a position check or comfort break. No chair movement is triggered.','Log comfort break','Comfort check',null]}[id];if(!info)return;modal(`<h2>${info[0]}</h2><p>${info[1]}</p><label>Optional note<textarea id="care-note" placeholder="Anything you’d like to remember…" maxlength="500"></textarea></label><button class="primary" id="confirm-care">${info[2]} ✓</button>`);$('#confirm-care').onclick=()=>{ensureDay();if(info[4])state[info[4]]++;log(info[3],$('#care-note').value.trim()||'Self-reported care activity',id==='drink'?'♒':'♡');close();toast('Added to your daily journal.');};}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)action(a.dataset.action,a.dataset.recipient);const n=e.target.closest('[data-view]');if(n)navigate(n.dataset.view);const m=e.target.closest('[data-mood]');if(m){state.mood=m.dataset.mood;log('Mood check-in',state.mood,'☺');toast('Your check-in is saved.');}const med=e.target.closest('[data-med]');if(med&&!med.disabled){const i=Number(med.dataset.med);modal(`<h2>Log ${i===0?'morning':'evening'} medication?</h2><p>Confirm only if you already took this medication according to your own prescribed plan. This is a sample tracker entry.</p><button class="primary" id="confirm-med">Yes, I have taken it</button>`);$('#confirm-med').onclick=()=>{ensureDay();if(!state.meds.includes(i)){state.meds.push(i);log('Medication logged',`${i===0?'Morning':'Evening'} sample entry · self-reported`,'⊕');}close();toast('Medication check-in saved.');};}});
$('#close-modal').onclick=close;
document.addEventListener('click',e=>{if(e.target.id==='download-report'){const url=URL.createObjectURL(new Blob([report()],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`wheelgentic-care-${day()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Report downloaded.');}if(e.target.id==='email-report'){const input=$('#caretaker-email');if(!input.value||!input.checkValidity()){input.reportValidity();input.focus();toast('Enter a valid recipient email.');return;}location.href=`mailto:${encodeURIComponent(input.value)}?subject=${encodeURIComponent('Wheelgentic daily care update')}&body=${encodeURIComponent(report())}`;toast('Email draft requested. Send it from your email app.');}if(e.target.id==='start-bath'){$('#session-state').textContent='Demo session active · Your four arms are simulated. Finish when ready to record a completed session.';e.target.parentElement.innerHTML='<button class="primary" id="finish-bath">Complete demo session ✓</button><button class="stop-button" id="stop-bath">Stop demo</button>';}if(e.target.id==='finish-bath'){ensureDay();state.baths++;log('Bathing session completed','Simulated session · no hardware connected','♡');close();toast('Demo bathing session logged.');}if(e.target.id==='stop-bath'){close();toast('Demo stopped. No completed session recorded.');}});
render();


