"""tests/fixture.py — test-only artifacts, generated not committed.

homography.pkl is deliberately NOT in git: it is specific to one camera on one
table, and a committed one silently ships a wrong transform to demo day.
Tests still need *a* transform, so they generate a synthetic one here, into a
clearly-named file that can never be mistaken for a real calibration.
"""
import os, pickle, sys
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, os.path.join(ROOT, "py"))

SYNTHETIC_PX = [[420., 210.], [880., 225.], [960., 520.], [340., 505.]]


SENTINEL = os.path.join(ROOT, ".homography-is-synthetic")


def ensure_homography(path=None):
    """Create a synthetic homography.pkl if none exists. Returns (path, made).

    DANGER, and the reason for the sentinel: this writes to the PRODUCTION
    filename. Run the suite at the venue after calibrating and it would
    overwrite a real calibration; worse, a leftover synthetic one is
    indistinguishable from a real one and the arm scrubs ~30cm off a person's
    forearm with no warning anywhere.

    So: it NEVER overwrites an existing file, and it drops a sentinel beside
    the one it creates. py/calibrate.load() shouts if the sentinel is present.

    THE SENTINEL FOLLOWS THE PATH, not this module's ROOT. It used to be the
    module-level SENTINEL constant, which is ROOT/.homography-is-synthetic no
    matter which path was written -- while calibrate.load() derives the
    sentinel from the dirname of the file it was HANDED. The two disagreed, so
    ensure_homography("/tmp/x/homography.pkl") produced a synthetic transform
    with no sentinel beside it and load() accepted it in SILENCE (measured: 0
    chars of output, no banner), which is exactly the ~30cm-off-a-forearm case
    the docstring above warns about. It also dropped a spurious sentinel at
    ROOT, making load() shout "TEST FIXTURE" over a real root calibration.
    Invisible in the suite because all four importers call this with no
    argument, so on any machine that already has homography.pkl the early
    return below fires and the creation branch never runs.
    """
    path = path or os.path.join(ROOT, "homography.pkl")
    if os.path.exists(path):
        return path, False
    import calibrate as C
    H = C.solve(SYNTHETIC_PX, verbose=False)
    pickle.dump(H, open(path, "wb"))
    # Same rule as calibrate.load(): beside the pickle, not beside this module.
    sentinel = os.path.join(os.path.dirname(os.path.abspath(path)) or ".",
                            ".homography-is-synthetic")
    open(sentinel, "w").write(
        "This homography.pkl was generated by tests/fixture.py from synthetic\n"
        "corner clicks. It is NOT a real calibration. Delete both files and\n"
        "run: python py/calibrate.py\n")
    return path, True


def ensure_recording(path=None, frames=180):
    """Create recordings/synthetic.jsonl if missing."""
    import json, math
    path = path or os.path.join(ROOT, "recordings", "synthetic.jsonl")
    if os.path.exists(path):
        return path, False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    rows = []
    for i in range(frames):
        t = 1000.0 + i / 30.0
        rows.append({"t": t,
                     "elbow": [520 + 8*math.sin(i/40), 400 + 4*math.cos(i/33)],
                     "wrist": [760 + 8*math.sin(i/40), 415 + 4*math.cos(i/33)]})
    open(path, "w").write("\n".join(json.dumps(r) for r in rows) + "\n")
    return path, True


if __name__ == "__main__":
    for fn in (ensure_homography, ensure_recording):
        p, made = fn()
        print(f"  {'created' if made else 'exists '}  {os.path.relpath(p, ROOT)}")
